version: "3.7"

services:
  php:
    build:
      context: .
      dockerfile: provision/docker/php/Dockerfile
      target: luxo_php
      args:
        APP_ENV: dev
    volumes:
      - ./:/var/www/app:rw,cached
      - ./provision/docker/php/conf.d/custom.dev.ini/:/usr/local/etc/php/conf.d/custom.ini
    depends_on:
      - db
      - mailer

  nginx:
    build:
      context: .
      dockerfile: provision/docker/nginx/Dockerfile
      target: luxo_nginx
    depends_on:
      - php
    volumes:
      - ./public:/var/www/app/public:ro
    ports:
      - "80:80"

  db:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: root

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      MYSQL_USERNAME: root
      MYSQL_ROOT_PASSWORD: root
    restart: always
    ports:
      - "8080:80"

  mailer:
    image: maildev/maildev
    ports:
      - "1080:80"
      - "1025:25"

  blackfire:
    image: blackfire/blackfire
    environment:
      # Exposes BLACKFIRE_SERVER_* environment variables from the host
      BLACKFIRE_SERVER_ID: 65d7fe72-fca9-4a3c-b068-e895200d89b7
      BLACKFIRE_SERVER_TOKEN: 01a8a4427541e4a59abd72561fd4e4bb55c69bcf4d134829ff5cb6335f9a46c7
